spring.application.name=CCtCAPI

spring.datasource.url=jdbc:sqlserver://LUSWST001904;instanceName=SQLEXPRESS;databaseName=CASINOCTC;encrypt=false;trustServerCertificate=true
spring.datasource.username=GSI
spring.datasource.password=GloryUSA1
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver


# Disable JPA auto config (since using JDBC)
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true


# Example app.cors.allowed-origins=http://localhost:4200,https://app.mycasino.com
app.cors.allowed-origins=http://localhost:4200
