spring.application.name=CCtCAPI

spring.datasource.url=jdbc:sqlserver://LUSWST001904;instanceName=SQLEXPRESS;databaseName=GGSCTC_CASINO;encrypt=false;trustServerCertificate=true
spring.datasource.username=GSI
spring.datasource.password=GloryUSA1
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

#Security 12 hours
app.jwt.access-token-expiration-ms=43200000 

# Hibernate for JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

#  JPA

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=GSI
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect


# Example app.cors.allowed-origins=http://localhost:4200,https://app.mycasino.com
app.cors.allowed-origins=http://localhost:4200
